### PR TITLE
My Lesson 3 Task 2 Done

### PR DESCRIPTION
**Pull request by iamipheco**
@promise-J
@ChidiPatrick

I'm done with my Lesson_3_Task_2 (Group B}
Please Kindly Check it out.

### CODE REVIEW

**Review by ChidiPatrick — APPROVED** [review]
Great job!

**Comment by iamipheco** [comment]
> Great job!

Thanks so much

**Review by ChidiPatrick — CHANGES_REQUESTED** [review]
For tablet screen size, make your "Recent posts" and "Categories" to be side by side

**Comment by iamipheco** [comment]
> For tablet screen size, make your "Recent posts" and "Categories" to be side by side

Alright

**Comment by iamipheco** [comment]
> For tablet screen size, make your "Recent posts" and "Categories" to be side by side

I'm done with the corrections, Please Can you kindly check that out and give me a go head to merge?

**Pull request merged**
